### ISSUE TITLE
Adding a function topvalue() in pqdict

### ISSUE THREAD

**Issue by ShivKJ** [nvictus/priority-queue-dictionary#17]
Hi,

Thanks for creating this simple yet useful library.

While using the lib, I find that sometimes we need to find the value of `pq[pq.top()]` or `pq.topitem()[1]` where `pq` 
is non-empty `maxpq`.

In general, I think, It will be useful to add a function `.topvalue()` in `pqdict` API.

Let me know your thoughts, and if you are okay, I will create a PR for this.

Thanks

**Comment by nvictus** [comment]
A very reasonable request. Sounds good to me!

**Comment by ShivKJ** [comment]
Thanks @nvictus. I created a [PR](https://github.com/nvictus/priority-queue-dictionary/pull/18), have a look.

**Comment by nvictus** [comment]
Merged and released. Thank you!
