### ISSUE TITLE
Key as Priority Element Instead of Value

### ISSUE THREAD

**Issue by GlacialBlaze** [nvictus/priority-queue-dictionary#5]
Is it possible that in the 'key' parameter, I specify the keys of the dictionary as the priority function?

Example:
a_dict = {'b': 1, 'a': 3 , 'c': 2}

Instead of: 
my_pqdict =  {'b': 1, 'c': 2, 'a': 3}     ...     ordered by value

I obtain this:
my_pqdict =  {'a': 3, 'b': 1, 'c': 2}     ...     ordered by key

It would really be helpful if the priority queue dictionary can do so.

**Comment by nvictus** [comment]
No, unfortunately that's not something `pqdict` can do, unless you put a copy of the key into the value and use a custom `precedes` function, but that's kind of hacky.

You might want to take a look at `SortedDict` in the [sorted containers](https://github.com/grantjenks/python-sortedcontainers) package.
